# Generated by Django 5.1.7 on 2025-04-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowerdetectionrecord',
            options={'verbose_name': '检测记录', 'verbose_name_plural': '检测记录'},
        ),
        migrations.RemoveField(
            model_name='flowerdetectionrecord',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='flowerdetectionrecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='flowerdetectionrecord',
            name='result',
        ),
        migrations.AddField(
            model_name='flowerdetectionrecord',
            name='image_result_path',
            field=models.CharField(default=1, max_length=255, verbose_name='结果图片路径'),
            preserve_default=False,
        ),
    ]
