# Generated by Django 5.2.9 on 2025-12-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0003_knowledgebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
