# Generated by Django 5.2.9 on 2025-12-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
