# Generated by Django 5.2.9 on 2026-01-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerdetectionrecord',
            name='video_timestamp',
            field=models.FloatField(blank=True, null=True, verbose_name='视频时间戳'),
        ),
    ]
